#Vaadin Copilot Integration Runtime Properties
#Mon Mar 02 08:53:40 CET 2026
endpoint=http\://127.0.0.1\:15396/vaadin/copilot-30ee9304-6dde-4d4b-84b9-8d6bb659f0f7
ide=eclipse
supportedActions=write,writeBase64,delete,undo,redo,refresh,showInIde,getModulePaths,compileFiles,restartApplication,getVaadinRoutes,getVaadinVersion,getVaadinComponents,getVaadinEntities,getVaadinSecurity,reloadMavenModule,heartbeat
version=1.0.0
